// A learned model is generated by parallax.train; no keyword/canary shortcut.
import weights from './weights.json';
export const modelName = weights.model_id;
export async function scoreTexts(texts:string[]):Promise<number[]> {
 if(weights.model_id==='untrained-disabled')throw new Error('Train a model before using detector B.');
 if((weights as any).backend==='minilm') {
  const response=await chrome.runtime.sendMessage({type:'classify',texts});
  if(response.error)throw new Error(response.error);return response.scores;
 }
 return texts.map(text=>{
   const tokens=text.toLowerCase().replace(/canary-[a-z0-9-]+/gi,'token').match(/[\p{L}\p{N}_]{2,}/gu)||[];
   const features=new Map<string,number>();
   for(let n=1;n<=2;n++) for(let i=0;i<=tokens.length-n;i++) {
     const term=tokens.slice(i,i+n).join(' '); features.set(term,(features.get(term)||0)+1);
   }
   const learned=weights.features as Record<string,number[]>;
   let norm=0;const values:number[][]=[];
   for(const [term,count] of features){
     const pair=learned[term];if(!pair)continue;
     const value=count*pair[0];norm+=value*value;values.push([value,pair[1]]);
   }
   norm=Math.sqrt(norm)||1;
   const logit=weights.intercept+values.reduce((s,[value,coef])=>s+value/norm*coef,0);
   return 1/(1+Math.exp(-logit));
 });
}
